---
title: "Intro to R; Revised"
author: "John Little (@libjohn) & Joel Herndon (@herndonj)"
date: "`r Sys.Date()`"
output: github_document
---
# README

- template code - https://is.gd/rcode
- rrev repo - https://is.gd/rrev2018

This repository contains [supporting datasets and files](https://rfun.library.duke.edu/intro2r/) for our **Intro to R** workshop by the [Data & Visualization Services Department](http://library.duke.edu/data), Duke University Libraries.  You can find more information about our future and past [workshops](http://library.duke.edu/data/news) 

- data are in the [data](data) directory of this repository

- our *guide* can be found at our [Rfun site](https://rfun.library.duke.edu/intro2r/).


## Outline

1. New R Notebook

    a. Render
    b. Literate Coding
        i. New Code Chunk:  *Ctrl+Alt+I*
        i. R Markdown, intro
    c. [`library(tidyverse)`](https://tidyverse.org)
    d. Hello World
    e. R Markdown, basic
        i. headings
        i. italics, bold
        i. links, lists

2. Load & View Tibble (data frame)

1. Data Structure & Data Types (brief)

1. [`dplyr`](http://dplyr.tidyverse.org/) -- part of tidyverse

    a. `filter` rows
    b. `arrange` rows by variables
    c. `select` columns
    d. `mutate` derive cells / new variables
    e. `count` column totals
    f. `summarize` grouping reports
    
1. **Now You Try It.**  Hands on exercises.

    1. [exercise_01.Rmd](exercise_01.Rmd)
    1. [exercise_02.Rmd](exercise_02.Rmd)
    1. [answers.Rmd](answers.Rmd)

1. Before we go on...  [final thoughts](ZZ_closing-thoughts.Rmd)

1. Visualize with `ggvis`  (syntactically simpler than ggplot2, but...)

    a. https://rfun.library.duke.edu/intro2r/visualization.html

1. Mapping in R

    b. https://rfun.library.duke.edu/intro2r/gis.html

1. Our Workshops

    a. R we having fun yet‽  https://rfun.library.duke.edu
    b. Full DVS [workshop series](https://library.duke.edu/data/news/past-workshops)
    
1. Questions:  [Walk-in schedule](https://library.duke.edu/data/about/schedule) and by appointment [Data Science Consulting](https://library.duke.edu/data/about)
    
## License

Shareable via Creative Commons: [CC-BY-NC](https://creativecommons.org/licenses/by-nc/4.0/)

